# Generated by Django 5.0.2 on 2024-02-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Donation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_customer',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='request_customer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='district',
        ),
        migrations.DeleteModel(
            name='Blood_Group',
        ),
        migrations.DeleteModel(
            name='Request_Customer',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
